version: '3.8'
services:
  app:
    build: .
    working_dir: /usr/src/app
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "15432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
