version: '3.8'
services:
  worker:
    profiles: [ "worker" ]
    build: .
    working_dir: /usr/src/app
    command: sh -c "deno run -A src/main.ts && deno task build"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/

  serve:
    profiles: [ "serve" ]
    build: .
    working_dir: /usr/src/app
    command: deno task serve
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "15432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
