--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article_topic; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.article_topic (
    article_id integer NOT NULL,
    topic_id integer NOT NULL
);


ALTER TABLE public.article_topic OWNER TO root;

--
-- Name: info; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.info (
    id integer NOT NULL,
    title text,
    link text,
    status text,
    source text,
    original text,
    date date,
    article text,
    created_at timestamp with time zone DEFAULT now(),
    article_title text,
    article_content text,
    slug text,
    url text
);


ALTER TABLE public.info OWNER TO root;

--
-- Name: info_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.info_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.info_id_seq OWNER TO root;

--
-- Name: info_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.info_id_seq OWNED BY public.info.id;


--
-- Name: topics; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.topics (
    id integer NOT NULL,
    name character varying(128),
    slug text
);


ALTER TABLE public.topics OWNER TO root;

--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.topics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.topics_id_seq OWNER TO root;

--
-- Name: topics_id_seq1; Type: SEQUENCE; Schema: public; Owner: root
--

CREATE SEQUENCE public.topics_id_seq1
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.topics_id_seq1 OWNER TO root;

--
-- Name: topics_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: root
--

ALTER SEQUENCE public.topics_id_seq1 OWNED BY public.topics.id;


--
-- Name: info id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.info ALTER COLUMN id SET DEFAULT nextval('public.info_id_seq'::regclass);


--
-- Name: topics id; Type: DEFAULT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.topics ALTER COLUMN id SET DEFAULT nextval('public.topics_id_seq1'::regclass);


--
-- Name: article_topic article_topic_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.article_topic
    ADD CONSTRAINT article_topic_pkey PRIMARY KEY (article_id, topic_id);


--
-- Name: info info_link_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.info
    ADD CONSTRAINT info_link_key UNIQUE (link);


--
-- Name: info info_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.info
    ADD CONSTRAINT info_pkey PRIMARY KEY (id);


--
-- Name: topics topics_id_key; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_id_key UNIQUE (id);


--
-- Name: topics unique_slug; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT unique_slug UNIQUE (slug);


--
-- Name: article_topic fk_article; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.article_topic
    ADD CONSTRAINT fk_article FOREIGN KEY (article_id) REFERENCES public.info(id) ON DELETE CASCADE;


--
-- Name: article_topic fk_topic; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.article_topic
    ADD CONSTRAINT fk_topic FOREIGN KEY (topic_id) REFERENCES public.topics(id);


--
-- Modernization additions
--

ALTER TABLE public.info ADD COLUMN IF NOT EXISTS retries integer DEFAULT 0;
ALTER TABLE public.info ADD COLUMN IF NOT EXISTS model_used text;
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS profile jsonb;
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS last_crawl_time timestamp with time zone;
ALTER TABLE public.topics ADD COLUMN IF NOT EXISTS config jsonb DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS public.candidates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
    title text NOT NULL,
    url text NOT NULL,
    snippet text DEFAULT '',
    source text NOT NULL,
    discovered_at timestamp with time zone NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending',
    relevance_score numeric,
    research_notes text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT candidates_topic_url_key UNIQUE (topic_id, url)
);

CREATE INDEX IF NOT EXISTS idx_candidates_status_discovered_at
    ON public.candidates (status, discovered_at DESC);

CREATE TABLE IF NOT EXISTS public.article_tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id integer NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    editor_notes text NOT NULL,
    priority integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    picked_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_article_tasks_status_priority
    ON public.article_tasks (status, priority DESC, created_at ASC);

CREATE TABLE IF NOT EXISTS public.articles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer NOT NULL UNIQUE REFERENCES public.article_tasks(id) ON DELETE CASCADE,
    topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
    title text NOT NULL,
    body text NOT NULL,
    slug text NOT NULL,
    url text NOT NULL,
    published_at timestamp with time zone NOT NULL DEFAULT now(),
    author_agent_version text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_articles_published_at
    ON public.articles (published_at DESC);

CREATE INDEX IF NOT EXISTS idx_articles_topic_published
    ON public.articles (topic_id, published_at DESC);

CREATE TABLE IF NOT EXISTS public.topic_notes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id integer NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
    note_type text NOT NULL,
    content text NOT NULL,
    source_url text,
    added_by_agent text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_topic_notes_topic_active
    ON public.topic_notes (topic_id, is_active, updated_at DESC);

--
-- PostgreSQL database dump complete
--

